name: Package Build

on:
  push:
    tags:
      - 'v*'

jobs:
  amd64-linux-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      - name: Build Linux amd64
        env:
          DEFAULT_CONF_FILE: /etc/cf-dynamic/cf-dynamic.conf
        run: cargo build --workspace -r && strip target/release/cf-dynamic
      - name: build-deb
        id: build-deb
        uses: kentik/pkg@v1.0.0-rc8
        with:
          name: cf-dynamic
          version: 1.0.0
          arch: x86_64
          format: deb
          package: package.yml
      - name: build-rpm
        id: build-rpm
        uses: kentik/pkg@v1.0.0-rc8
        with:
          name: cf-dynamic
          version: 1.0.0
          arch: x86_64
          format: rpm
          package: package.yml
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}          
          files: |
            target/release/cf-dynamic
            ${{ steps.build-deb.outputs.package }}
            ${{ steps.build-rpm.outputs.package }}
